import { ref } from 'vue';

export const availableScores = ref([
  { name: '吉他与孤独与蓝色星球', path: `${import.meta.env.BASE_URL}scores/吉他与孤独与蓝色星球.gpx` },
  { name: '春日影', path: `${import.meta.env.BASE_URL}scores/春日影.gp` },
  { name: 'Canon Rock', path: 'https://www.alphatab.net/files/canon.gp' },
  // Canon Rock 是目前用来进行全面测试的（多音轨，metadata完整）
  // { name: '[东方アレンジ]碎月 指弹', path: `${import.meta.env.BASE_URL}score/碎月-指弹(东方アレンジ).gpx`},
  // 不知道为何不支持这个gpx文件
  // { name: '妖怪の山',path: `${import.meta.env.BASE_URL}score/妖怪の山.gpx`},
  // 这个文件也不支持
  { name: '东方妖妖梦 - 幽雅に咲かせ、墨染の桜 ～ Border of Life (Drop D)', path: `${import.meta.env.BASE_URL}scores/东方妖妖梦 - 幽雅に咲かせ、墨染の桜　～ Border of Life(Drop D).gp5` },
  // { name: '[因幡輝哉]廃獄ララバイ',path: `${import.meta.env.BASE_URL}score/[因幡輝哉]廃獄ララバイ.mid`},
  // 目前暂时不支持midi文件
  { name: 'Lycoris Recoil 花の塔', path: `${import.meta.env.BASE_URL}scores/Lycoris Recoil 花の塔.gp` },
  { name: 'U.N. Owen Was Her', path: `${import.meta.env.BASE_URL}scores/U.N. Owen Was Her.gp5` },
  { name: '东方永夜抄 恋色マスタースパーク 指弹', path: `${import.meta.env.BASE_URL}scores/[东方永夜抄]恋色マスタースパーク 指弹.gp5` },
  { name: '东方风神绿 ネイティブフェイス 指弹', path: `${import.meta.env.BASE_URL}scores/[东方风神绿]ネイティブフェイス 指弹.gp5` },
  { name: '柔和碎月', path: `${import.meta.env.BASE_URL}scores/【东方】-柔和碎月.gp5` },
  { name: '东方永夜抄 - 懐かしき東方の血', path: `${import.meta.env.BASE_URL}scores/东方永夜抄 - 懐かしき東方の血.gpx` },
  { name: '废狱', path: `${import.meta.env.BASE_URL}scores/废狱.gpx` },
  { name: '改·色は匂へど散りぬるを', path: `${import.meta.env.BASE_URL}scores/改·色は匂へど散りぬるを.gpx` },
  { name: '进击的巨人op 紅蓮の弓矢 english notation', path: `${import.meta.env.BASE_URL}scores/进击的巨人op 紅蓮の弓矢 english notation.gp5` },
  { name: '上海红茶馆', path: `${import.meta.env.BASE_URL}scores/上海红茶馆.gp5` },
  { name: '碎月-指弹(东方アレンジ)', path: `${import.meta.env.BASE_URL}scores/碎月-指弹(东方アレンジ).gpx` },
  { name: 'おてんば恋娘', path: `${import.meta.env.BASE_URL}scores/おてんば恋娘.gp5` },
  { name: 'ギターと孤独と蒼い惑星', path: `${import.meta.env.BASE_URL}scores/ギターと孤独と蒼い惑星.gp` },
  { name: 'ギターと孤独と蒼い惑星', path: `${import.meta.env.BASE_URL}scores/ギターと孤独と蒼い惑星.gp5` },
  { name: 'Like A Star (Piano)', path: `${import.meta.env.BASE_URL}scores/archive/11.Like A Star(Piano) 金永所 Utopia.gp` },
  { name: 'Blossom', path: `${import.meta.env.BASE_URL}scores/archive/blossom.gp` },
  { name: 'Blossom', path: `${import.meta.env.BASE_URL}scores/archive/blossom.gpx` },
  { name: 'Cherry Blossom Time', path: `${import.meta.env.BASE_URL}scores/archive/Cherry Blossom Time(樱花盛开的时候十周年版).gpx` },
  { name: 'DEPAPEPE - START', path: `${import.meta.env.BASE_URL}scores/archive/DEPAPEPE - START.gp5` },
  { name: 'DEPAPEPE - 風向儀', path: `${import.meta.env.BASE_URL}scores/archive/DEPAPEPE - 風向儀.gp4` },
  { name: 'DEPAPEPE - HI-D!', path: `${import.meta.env.BASE_URL}scores/archive/DEPAPEPE-HI-D!.gp4` },
  { name: 'DEPAPEPE - over the sea', path: `${import.meta.env.BASE_URL}scores/archive/DEPAPEPE-over the sea.gpx` },
  { name: 'DEPAPEPE - Swingin Happy Xmas', path: `${import.meta.env.BASE_URL}scores/archive/DEPAPEPE-SwinginHappy_Xmas.gp4` },
  { name: 'DEPAPEPE - Wedding Bell', path: `${import.meta.env.BASE_URL}scores/archive/DEPAPEPE-Wedding_Bell.gp4` },
  { name: 'DEPAPEPE - いい日だったね', path: `${import.meta.env.BASE_URL}scores/archive/DEPAPEPE-いい日だったね.gp4` },
  { name: 'DEPAPEPE - 午后柠檬树下的阳光', path: `${import.meta.env.BASE_URL}scores/archive/DEPAPEPE-午后柠檬树下的阳光.gp5` },
  { name: 'HI-D', path: `${import.meta.env.BASE_URL}scores/archive/HI-D.gp` },
  { name: 'Lemon', path: `${import.meta.env.BASE_URL}scores/archive/Lemon.gpx` },
  { name: 'Loser', path: `${import.meta.env.BASE_URL}scores/archive/Loser.gpx` },
  { name: 'Memories (Live版)', path: `${import.meta.env.BASE_URL}scores/archive/Memories (Live版) 金永所 tab by Kevin.gp` },
  { name: '鲸歌', path: `${import.meta.env.BASE_URL}scores/archive/《鲸歌》陈亮&宋依凡.gp` },
  { name: 'メトロノーム', path: `${import.meta.env.BASE_URL}scores/archive/メトロノーム.gpx` },
  { name: '夏天的风', path: `${import.meta.env.BASE_URL}scores/archive/夏天的风.gp` },
  { name: '夜空中最亮的星', path: `${import.meta.env.BASE_URL}scores/archive/夜空中最亮的星.gpx` },
  { name: '奇妙能力歌', path: `${import.meta.env.BASE_URL}scores/archive/奇妙能力歌.gpx` },
  { name: '岸部真明 - 樹氷の輝き', path: `${import.meta.env.BASE_URL}scores/archive/岸部真明 - 樹氷の輝き.gp5` },
  { name: '打上花火', path: `${import.meta.env.BASE_URL}scores/archive/打上花火.gpx` },
  { name: '灰色と青', path: `${import.meta.env.BASE_URL}scores/archive/灰色と青.gpx` },
  { name: '病名は愛だった', path: `${import.meta.env.BASE_URL}scores/archive/病名は愛だった.gpx` },
  { name: '童话镇', path: `${import.meta.env.BASE_URL}scores/archive/童话镇.gpx` },
  { name: '蝴蝶结 - Aimer', path: `${import.meta.env.BASE_URL}scores/archive/蝴蝶结 - Aimer.gpx` },
]);

/*
  { name: '',path: `${import.meta.env.BASE_URL}score/`},
*/